name: kinova_reach_cube

task_name: kinova_reach_cube

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [8]
      type: low_dimx
  action:
    shape: [6]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.kinova_dataset.KinovaDataset
  zarr_path: data/cube_reach_test.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
