name: 720_kinova_bottle_cubes

task_name: 720_kinova_bottle_cubes

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [8]
      type: low_dimx
  action:
    shape: [7]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.weighted_kinova_dataset.WeightedKinovaDataset
  zarr_path: data/bottle_cubes_with_weights.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.0
  max_train_episodes: 90
